### ISSUE TITLE
crosses initialization of 'int ni' error when compiling on Ubuntu 20.04 and GCC 9.3.0

### ISSUE THREAD

**Issue by bzack** [vdemichev/DiaNN#37]
I was trying to compile on Ubuntu 20.04 and GCC 9.3.0 and received the error below. The newer GCC compiler may be more strict. I was able to compile successfully on Ubuntu 18.04

gcc -O3 -static -I. -I./include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H ./src/expat-2.2.0/xmlparse.c -c
gcc -O3 -static -I. -I./include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H ./src/expat-2.2.0/xmlrole.c -c
gcc -O3 -static -I. -I./include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H ./src/expat-2.2.0/xmltok.c -c
ar rcs libmstoolkitlite.a adler32.o compress.o crc32.o deflate.o inffast.o inflate.o infback.o inftrees.o trees.o uncompr.o zutil.o xmlparse.o xmlrole.o xmltok.o mzp.MSNumpress.o mzp.mzp_base64_lite.o mzp.BasicSpectrum_lite.o mzp.mzParser_lite.o mzp.RAMPface_lite.o mzp.saxhandler_lite.o mzp.saxmzmlhandler_lite.o mzp.saxmzxmlhandler_lite.o mzp.Czran_lite.o mzp.mz5handler_lite.o mzp.mzpMz5Config_lite.o mzp.mzpMz5Structs_lite.o mzp.BasicChromatogram_lite.o mzp.PWIZface_lite.o Spectrum.o MSObject.o mzMLWriter.o pepXMLWriter.o MSReaderLite.o
g++ -o ../diann-linux ../src/diann.cpp -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++17 -lstdc++fs -fpermissive -O3 -mfpmath=sse -msse2 -march=core2 -w -L. -lmstoolkitlite -I. -I./include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H
../src/diann.cpp: In member function 'void Library::max_lfq_quant(std::vector<PG>*, std::vector<Lock>*, double, bool)':
../src/diann.cpp:5113:4: error: jump to label 'save'
 5113 |    save:
      |    ^~~~
../src/diann.cpp:5066:10: note:   from here
 5066 |     goto save;
      |          ^~~~
../src/diann.cpp:5069:8: note:   crosses initialization of 'int ni'
 5069 |    int ni = indices.size();
      |        ^~
make: *** [Makefile:30: all] Error 1
root@2931130497d9:/diann/mstoolkit# gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by vdemichev** [comment]
Hi Ben,

Many thanks for the feedback! I will look into this.
Meanwhile, I would suggest just compiling with GCC 7 and then copying the binary to the target system: the binary is statically linked, so should be portable.

Best wishes,

Vadim
